### ISSUE TITLE
Use NuGet V3 API for package restore

### ISSUE THREAD

**Issue by skofman1** [Microsoft/ApplicationInsights-ServiceFabric#101]
I see in you [NuGet.config](https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/773d9cb05d7f606634490f5d7e695f00ab30c1d1/NuGet.config) that you are still using NuGet's V2 API. 
We strongly recommend moving to V3 API as it provides more reliable builds and [security improvements](https://blog.nuget.org/20180810/Introducing-Repository-Signatures.html).

The change is super simple:
Replace `https://www.nuget.org/api/v2/` with `https://api.nuget.org/v3/index.json`

**Comment by yantang-msft** [comment]
@skofman1 Thanks for letting us know. Fixed.
