### ISSUE TITLE
Actor Reminders share OperationId

### ISSUE THREAD

**Issue by profet23** [microsoft/ApplicationInsights-ServiceFabric#105]
It seems that all reminders are being recorded with the same OperationId. I have a long running actor acting as a sort of cron job. It is repeatedly called via an actor reminder for the lifetime of the application. All operations it performs get recorded together which makes parsing these time consuming. How can I split each reminder executing into separate Operations with unique OperationIds?

**Comment by yantang-msft** [comment]
@profet23 Have you looked at [StartOperation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking)?

**Comment by profet23** [comment]
Thank you @yantang-msft. I agree that this is a good workaround. But still feel each reminder invocation is a separate operation. I dunno. I guess it's debatable.

**Comment by yantang-msft** [comment]
@profet23 I'm glad you can work around this issue.
I agree with you each invocation is a separate operation. To make this happen, it requires some modifications in the SF framework, which we currently don't have any plan on that. Sorry about that.
