### ISSUE TITLE
Expose Request\Response events

### ISSUE THREAD

**Issue by festivus** [microsoft/ApplicationInsights-ServiceFabric#106]
I would like to use ServiceRemotingServiceEvents.SendResponse to do global exception handling\logging. The problem is there is no way to say I want my SendResponse to be called before yours, so sometimes the exception is logged after the app insights operation is finished in your SendResponse, so my exception is not correlated to any of the messages in the chain. Could you expose events before closing the operation?

**Comment by yantang-msft** [comment]
@festivus So we register our event handler at [here](https://github.com/microsoft/ApplicationInsights-ServiceFabric/blob/master/src/ApplicationInsights.ServiceFabric.Native.Shared/RequestTrackingModule/ServiceRemotingServerEventListener.cs#L37), which is triggered in initializing the ```ServiceRemotingRequestTrackingTelemetryModule```.
Can you try to register your SendReponse event handler before initializing ```ServiceRemotingRequestTrackingTelemetryModule```?
