### ISSUE TITLE
Update nuspecs before the next release

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/ApplicationInsights-ServiceFabric#11]
Although we can hand editing some of the package info in nuget.org, it will save time in the long run to make the info accurate in nuget spec files. Could you please update the info there?

**Comment by nizarq** [comment]
The following commit already takes care of that.  Let me know if that doesn't cover something. 

https://github.com/Microsoft/ApplicationInsights-ServiceFabric/commit/82d10b0f0a0cc6478563e0c6261a7a8420d9fdb1
