### ISSUE TITLE
What TelemetryChannel is recommended to be used in SF

### ISSUE THREAD

**Issue by BoeseB** [microsoft/ApplicationInsights-ServiceFabric#110]
Thanks for this library, the correlation tracking in interservice calls is really helpful. But I am still not sure how to use this properly in none ASP.Net services. While @yantang-msft provided a good example [here](https://github.com/yantang-msft/service-fabric-application-insights-example), I still got following questions:

1. Do we get more reliability by using `ServerTelemetryChannel ` over `InMemoryChannel` or is this already handled by the `Microsoft.ApplicationInsights.ServiceFabric.Native`  package?
2. Do we need to call Flush on Service Shutdown or is this done by the package? 
    If flush should be called, where is the right place to do so? 
          a) At the end of RunAsync
          b) In OnCloseAsync
          c) Somewhere else (are there any extension points on the ServiceFabricRuntime like shutdown events to better hook into this and call such things transparently to the actual service implementation?)

**Comment by yantang-msft** [comment]
1. You will get an authoritative answer for this question under this repo: https://github.com/microsoft/ApplicationInsights-dotnet. But I think it's safe to assume ```ServerTelemetryChannel``` has better performance and is used by default.
2. This package doesn't handle shutdown gracefully, and the ```TelemetryClient``` is a private member created [here](https://github.com/microsoft/ApplicationInsights-ServiceFabric/blob/master/src/ApplicationInsights.ServiceFabric.Native.Shared/DependencyTrackingModule/ServiceRemotingDependencyTrackingTelemetryModule.cs#L20).
