### ISSUE TITLE
Additional properties not showing in Application Insights .NET framework

### ISSUE THREAD

**Issue by inkey** [microsoft/ApplicationInsights-ServiceFabric#111]
I have added Microsoft.ApplicationInsights.ServiceFabric.Native package to my stateful project .net

I have added   `FabricTelemetryInitializerExtension.SetServiceCallContext(this.Context)`; to my RunAsync method.

I am loging to insights as follows

```
           TelemetryClient tclient = new TelemetryClient(new icrosoft.ApplicationInsights.Extensibility.TelemetryConfiguration("InstrumationKey"));
            tclient.TrackEvent("TEST");
```

However i am not seeing any of the context information in the application insight logs. I do see the TEST log.

Am i missing something i thought that these would be added when i genetered my logs?

**Comment by yantang-msft** [comment]
@inkey The context are added through TelemetryIntializer, which is configured in the ApplicationInsights.config file in your case, so you need to create a telemetry client from that config so the TelemetryInitializer can take effect.
Try ```TelemetryClient tclient = new TelemetryClient(TelemetryConfiguration.Active)```. More info at [here](https://docs.microsoft.com/en-us/azure/azure-monitor/app/console#using-config-file).
