### ISSUE TITLE
W3C Trace-Context Support

### ISSUE THREAD

**Issue by festivus** [microsoft/ApplicationInsights-ServiceFabric#113]
Do you support or plan on supporting Application Insights move to W3C Trace-Context for correlation headers? I do not get correlation when this feature is turned on. I have to do the following to get correlation working again:

Activity.DefaultIdFormat = ActivityIdFormat.Hierarchical;
Activity.ForceDefaultIdFormat = true;

**Comment by yantang-msft** [comment]
@festivus Unfortunately, we don't have a plan on any new features. Feel free to contribute though.
