### ISSUE TITLE
Combine Service Fabric Actor + ApplicationInsights + ILogger

### ISSUE THREAD

**Issue by jay1891** [microsoft/ApplicationInsights-ServiceFabric#116]
We require to combine an actor that uses application insights and this together with specific iloggers inside the actor service.

We use the approach described in the issue: https://github.com/microsoft/ApplicationInsights-ServiceFabric/issues/88 on a .net 5 platform. But when we create a LoggerFactory, starting from a service collection and that uses the same instrumentation key then this telemetry client it is not logging any information.

The class is the following.

What could be the reason for this?

    public class SfActorService : ActorService
    {
        #region CONSTANTS
        public const string NLogConfigFileNameForServiceFabric = "NLog.ServiceFabric.config";
        #endregion

        #region PROPERTIES
        public IConfiguration Configuration { get; }
        #endregion

        #region CONSTRUCTORS
        public SfActorService(
            StatefulServiceContext context,
            ActorTypeInformation actorTypeInfo,
            //IConfiguration configuration,
            Func<ActorService, ActorId, ActorBase> actorFactory = null,
            Func<ActorBase, IActorStateProvider, IActorStateManager> stateManagerFactory = null,
            IActorStateProvider stateProvider = null,
            ActorServiceSettings settings = null)
            : base(context, actorTypeInfo, actorFactory, stateManagerFactory, stateProvider, settings)
        {
            //
            ServiceCollection services = new ServiceCollection();

            // Create Configuration
            {
                // Init
                ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();

                // Add configuration files
                configurationBuilder.AddSeafarWebAppSettings();
                Configuration = configurationBuilder.Build();

                // Register Configuration
                services.AddSingleton<IConfiguration>(Configuration);
            }

            // Add ApplicationInsights
            // https://github.com/microsoft/ApplicationInsights-ServiceFabric/issues/88
            ITelemetryInitializer telemetryInitializer = null;
            string applicationInsightsInstrumentationKey = Configuration[ConfigurationKeys.ApplicationInsights_InstrumentationKey];
            {
                telemetryInitializer = FabricTelemetryInitializerExtension.CreateFabricTelemetryInitializer(this.Context);
                TelemetryConfiguration telemetryConfiguration = TelemetryConfiguration.Active;
                telemetryConfiguration.InstrumentationKey = applicationInsightsInstrumentationKey;
                telemetryConfiguration.TelemetryInitializers.Add(telemetryInitializer);

                var requestTrackingModule = new ServiceRemotingRequestTrackingTelemetryModule();
                var dependencyTrackingModule = new ServiceRemotingDependencyTrackingTelemetryModule();
                requestTrackingModule.Initialize(telemetryConfiguration);
                dependencyTrackingModule.Initialize(telemetryConfiguration);
            }

            // Create Logger
            {
                services.AddLogging(logging =>
                {
                    // Add Logging
                    logging.AddConfiguration(Configuration.GetSection(ConfigurationKeys.Logging));

                    // Add Logging - NLog
                    logging.AddNLog(NLogConfigFileNameForServiceFabric);

                    // Add Logging - ApplicationInsights
                    logging.AddApplicationInsights(applicationInsightsInstrumentationKey);
                    logging.AddFilter<ApplicationInsightsLoggerProvider>("", LogLevel.Warning);
                });
            }

            // Init Services
            IServiceProvider serviceProvider = services.BuildServiceProvider();

            // Init Logging (Monet)
            AppMsLogging.LoggerFactory = serviceProvider.GetService<ILoggerFactory>();
            AppMsLogging.CreateLogger<SfActorService>().LogError("ERRROOOOR");
        }
        #endregion
    }

**Comment by yantang-msft** [comment]
@jay1891 what you if don't set filter level to Warning? Does AppInsights with Actor ever worked for you and just stopped working after switching to .Net 5?

**Comment by jay1891** [comment]
@yantang-msft

> @jay1891 what you if don't set filter level to Warning? Does AppInsights with Actor ever worked for you and just stopped working after switching to .Net 5?

AppInsights works on our net5 web app and also we see an exception being logged in an net5 actor method if we throw there an exception and this by using #88. But using our own telemetry client, or using DI with a service collection, or using serilog is not creating error logs.

**Comment by yantang-msft** [comment]
@jay1891 AppInsights configuration is very tricky, it's different depending on the run time (.net, .net core) and app (console, asp.net core). My gut feeling is App Insights is not setup correctly, while this project is more for enrich the telemetry once AppInsights is setup correctly.
I created a project with some examples before which may help you setup the AppInsights: https://github.com/yantang-msft/service-fabric-application-insights-example

**Comment by jay1891** [comment]
> 
> 
> @jay1891 AppInsights configuration is very tricky, it's different depending on the run time (.net, .net core) and app (console, asp.net core). My gut feeling is App Insights is not setup correctly, while this project is more for enrich the telemetry once AppInsights is setup correctly.
> I created a project with some examples before which may help you setup the AppInsights: https://github.com/yantang-msft/service-fabric-application-insights-example

@yantang-msft Thank you for the info. I got some logging working also with the help of implementing a specific ApplicationInsightsLoggerProvider. I also noticed I was looking at the live metrics, as I configured them for our web app, but the actors where not configured with it (in the sample and #88 ). This created some confusion, as I was not seeing all our logging activity in the live metrics. But some logging was actually available in the core appinsights logging. So, sorry for the confusion. After activating the live metrics on our actors I was seeing what I was hoping to see.

Thank you for your help!
