### ISSUE TITLE
[Proposal] Add support for automatic telemetry (request and dependency) collection for service remoting

### ISSUE THREAD

**Issue by nizarq** [Microsoft/ApplicationInsights-ServiceFabric#14]
Application Insights already has pretty good support for http based service communication. That is, application insights modules can automatically intercept http based communication and generate request and dependency telemetry. 

In Service Fabric, however, it is pretty common for services to communicate over [Service Remoting](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting). The proposal is to add automatic AI telemetry collection of service remoting stack as well.

**Comment by brahmnes** [comment]
Now implemented with the new Correlating* classes.
