### ISSUE TITLE
Using this with Actors & Service Bus

### ISSUE THREAD

**Issue by aarondandy** [Microsoft/ApplicationInsights-ServiceFabric#18]
I'm having trouble getting this to work well with actors and service bus. Is there any guidance as to how we should get this information added to our telemetry when logging events from within an actor instance or a message handler?

**Comment by brahmnes** [comment]
Hi Aaron,

Do you have specifics on what's the problem? Is it data not getting logged to Application Insights, or they aren't logged with enough contextual information?

**Comment by aarondandy** [comment]
If a request comes in through a Service Fabric listener it seems that the context information is added as I would expect, which is helpful. When I have code that may be executing within other usage scenarios however I either get no information appended at all or only the ServiceFabric.NodeName item. I have not found a pattern yet as to when I get the NodeName only vs. nothing. I think given that we are already using Serilog and that we are having enough trouble with this with our crazy/not-so-crazy stuff we are doing that we may just make our own quick little enricher for this. That said I will be checking back here from time to time and am willing to answer any questions you may have.

Here are some of the scenarios where we are tossing AI events around:

## API Requests

Works great. We wired it up in the listener, the things do what they are supposed to do.

## Actor Methods

Does not work at all. Hooking into both the ActorService instantiation as well as the Actor instance instantiation appears to not be related to the same contexts that would be used to handle requests, so it seems that attributes are not populated often for actor method calls, but sometimes we get one that has a NodeName set at least. I have not yet tried to setup the context in each method yet though because to be blunt I really don't want to have to do that.

## Stateless Services with Timers

Does not really work. We have a stateless service using a `System.Timers.Timer` ... and I don't want to go into that *but* what is interesting is within the `Elapsed` handler we make a call to `SetServiceCallContext` and pass it the context. This seems to work OK sometimes but when we look closely at the telemetry I think it is just using the values that may have been populated for another context/thread that was used to setup the services.

## Service Bus

Does not work. When we handle a message we are calling `SetServiceCallContext` on both the RunAsync as well as the OnMessage bits to be sure that we add the information to AI as doing so within the service startup does not make its way to handler methods it seems. In these case we don't see any attributes added at all for Service Fabric.

**Comment by brahmnes** [comment]
Hi Aaron,

There is indeed a challenge where the ServiceContext may not be there sometimes. One option is when the service is constructed, call FabricTelemetryInitializerExtension.CreateFabricTelemetryInitializer, and associate the initializer with the TelemetryClient you use, then use the same TelemetryClient object for all the logging. This way, the initializer has its own values and won't look at the call context.

Let me know if that solves all your problems.
