### ISSUE TITLE
Create Live Metrics Stream for Service Fabric Cluster

### ISSUE THREAD

**Issue by Expecho** [Microsoft/ApplicationInsights-ServiceFabric#19]
I managed to create a working Live Metrics Steam environment in Application Insights that reflects the state of the cluster and the deployed applications, see https://github.com/DeHeerSoftware/Azure-Service-Fabric-Logging-And-Monitoring.

Is this on the roadmap for this repo as well? Is there a roadmap of upcoming features?

**Comment by brahmnes** [comment]
Which specific feature are you referring to? Your repo mentioned several things, such as using serilog, and intercepting requests by hooking into ASP.NET core.

**Comment by Expecho** [comment]
I specifically refer to the Live Metrics Stream. It shows the cpu and memory usage of the machines in the cluster and combined with the tracing of requests you have implemented in this repo it will show the rate of requests per second etc. See also https://azure.microsoft.com/en-us/blog/live-metrics-stream/

**Comment by brahmnes** [comment]
If you are referring to tracing of ASP.NET requests, that's handled by the App Insights ASP.NET core SDK: https://github.com/Microsoft/ApplicationInsights-aspnetcore
If you are referring to tracing of service remoting requests, yes, a recent check in has been made to enable that, though it's not completely finished yet. We don't have plans for live stream support yet. Our current main focus is auto-logging as much of the interesting events as possible without manual instrumentation.

**Comment by GuptaParitosh** [comment]
@brahmnes I am not able to see Incoming Request and outgoing Request Telemetry in live telemetry Stream Section in App insights. It shows only Server health of the machines in cluster.
 I am able to do tracing and exceptions log in application Insights for micro-services (service fabrics) using Microsoft.AI.Web Nu-Get Package. 

Is their any way by which we can capture Telemetry for Live Metrics Stream and also for overview timeline section????

 Do let me know.

**Comment by brahmnes** [comment]
@Sergeykanzhelev, who may know the answer for sure about live stream.
For live stream, I think you need the Quick Pulse telemetry, which this SDK currently doesn't do. However, this SDK depends on other pieces of AppInsights SDK, like Microsoft.ApplicationInsights,Web for the ASP.NET core case, so you can use Quick Pulse from that.

In my testing, I do see data in the overview timeline, like server response time and # of server requests. Perhaps you can go to search and see if you are getting any data on requests?

**Comment by Expecho** [comment]
@GuptaParithos for the Live Stream you do indeed need the Quick Pulse telemetry but it requires some setup, see the initialization in our repo, https://github.com/DeHeerSoftware/Azure-Service-Fabric-Logging-And-Monitoring/blob/master/src/ServiceFabric.Logging/ApplicationInsights/LiveStreamProvider.cs. You will need to include some additional assemblies as outline in the repo as well.

**Comment by SergeyKanzhelev** [comment]
Some details on live stream enablement http://apmtips.com/blog/2017/02/13/enable-application-insights-live-metrics-from-code/ 

Sorry, missed this question.
