### ISSUE TITLE
When is the next nuget release planned?

### ISSUE THREAD

**Issue by ThiemeNL** [Microsoft/ApplicationInsights-ServiceFabric#20]
Hi, 

When can we expect to have a new nuget release? 

The correlation support for remoting will be really nice. 
https://github.com/Microsoft/ApplicationInsights-ServiceFabric/commit/12c217cc044235dc2c5e59942248009e0dfe6ddc

Thanks,
Thieme

**Comment by brahmnes** [comment]
Thanks, good to know this is useful. Any feedback would be appreciated.
Still need to test and polish, probably within the next few weeks.

**Comment by ThiemeNL** [comment]
Thanks, I'm looking forward to it.

**Comment by yantang-msft** [comment]
We've just published 1.1.0-beta1 with the correlation support. Any feedback is welcomed.
https://www.nuget.org/packages/Microsoft.ApplicationInsights.ServiceFabric.Native/1.1.0-beta1
