### ISSUE TITLE
Fabric telemetry data is not available in destination service.

### ISSUE THREAD

**Issue by n3gwave** [Microsoft/ApplicationInsights-ServiceFabric#25]
Assuming we have two services A and B, both with OwinCommunicationListener and FabricTransportServiceRemotingListener with CorrelatingRemotingMessageHandler in place, when calling service A using REST which in turn calls service B using internal fabric communication then correlation data is propagated correctly but service fabric data (I mean ServiceName, ApplicationName. I know that RoleInstance and RoleName is taken from environment) is missing in telemetry requests created in CorrelatingRemotingMessageHandler in service B, even though FabricTelemetryInitializer is configured correctly and FabricTelemetryInitializerExtension is called in CreateServiceInstanceListeners method in both services. It does work in service A. Is it on purpose or is it an issue?

**Comment by yantang-msft** [comment]
Is it a problem even without the CorrelatingRemotingMessageHandler? This message handler has nothing to do with collecting the service fabric data.

One possible reason of not getting service fabric data is the logicalCallContext (which you set using FabricTelemetryInitializerExtension.SetServiceCallContext) get lost during managed/unmanaged thread transition. If this happens in the callstack, here is one option https://github.com/Microsoft/ApplicationInsights-ServiceFabric/issues/18
