### ISSUE TITLE
Reference to type 'IServiceRemotingMessageHandler' claims it is defined in 'Microsoft.ServiceFabric.Services.Remoting', but it could not be found

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/ApplicationInsights-ServiceFabric#28]
Looks like the IServiceRemotingMessageHandler has changed namespace in SF 2.8, which is a breaking change.

This break the feature for tracing remote calls using SF remoting (V1)

**Comment by brahmnes** [comment]
Hi Mikael,

Thank you for reporting. This is an important blocking issue and we will look into it.

**Comment by mikanyg** [comment]
Has this issue been fixed with the V2 beta release?

**Comment by brahmnes** [comment]
Hi Mikael,

Yes, it's fixed now in the 2.0 beta release of this nuget.
