### ISSUE TITLE
Service Remoting Trace Correlation using Actors

### ISSUE THREAD

**Issue by esbenbach** [Microsoft/ApplicationInsights-ServiceFabric#35]
I am trying to get the service remoting correlation to work using actors.
Following the instructions of the README.md it  should be straight forward, but of course there are subtle differences when using Actors instead of stateless services.

On the client side I create a proxy as follows:

	string actorUrl = "fabric:/MyApp/MyActor";
	Guid id = Guid.NewGuid();
	var proxyFactory = new CorrelatingActorProxyFactory(null, callbackClient => new 
	FabricTransportServiceRemotingClientFactory(callbackClient: callbackClient));
	return proxyFactory.CreateActorProxy<TReadModelBuilder>(new Uri(actorUrl), new ActorId(id));	

On the Actor side I have an "AiActorService" class that overrides CreateServiceReplicatListeners as follows:

	protected override IEnumerable<ServiceReplicaListener> CreateServiceReplicaListeners()
	{
		var transportSettings = new FabricTransportRemotingListenerSettings
		{
			EndpointResourceName = "MyActorServiceEndpoint",
		};

		var result = new ServiceReplicaListener[1]
		{
			new ServiceReplicaListener(context => new FabricTransportActorServiceRemotingListener(context, new CorrelatingRemotingMessageHandler(context, this), transportSettings))
		};
		return result;
	}

However when using the proxy, i get an exception saying "Interface id {id} is not implemented by object {proxy}"

Now looking at the replica listener the {id} does not correspond with the interface Id I find in the exception, so obviously something is wrong. But reverting back to the "default listener" (i.e. removing the AiActorService and just using the plain old ordinary actor service) everything works just fine.

Either there is something I am doing wrong because I don't understand what i am doing, or there is an issue with listener/proxy implementation.

Anyone who have got this working, or otherwise might be able to shed some light on this is appreciated.

**Comment by brahmnes** [comment]
On the client side, you should pass in a service context object to CorrelationActorProxyFactory. Without it, you lose a lot of contextual information, such as service name, about the traces logged by the client.

On the actor side, try calling the CorrelatingRemotingMessageHandler constructor that takes the ActorService, which in you case it's just "this". It will pull out the service context from the actor service. The other constructor you are calling, that takes ServiceContext and IService, should be used only for non-actor services.

**Comment by brahmnes** [comment]
Hi Esben,

I assume my response answered your question. If not, feel free to reactivate this issue.
