### ISSUE TITLE
Support for .Net Core 2?

### ISSUE THREAD

**Issue by Eneuman** [Microsoft/ApplicationInsights-ServiceFabric#36]
What is the plan for releasing a nuget package supporting the new .Net 2.0 Core templates in ServiceFabric Tools 2.0 preview?

**Comment by nizarq** [comment]
Thanks for asking. I'll look into it and give an update soon.

**Comment by Eneuman** [comment]
Any news about this ?

**Comment by brahmnes** [comment]
Thanks for checking. This is still work in progress

**Comment by brahmnes** [comment]
Hi Eneuman

We did some investigations and it appears the ApplicationInsight.ServiceFabric nuget should just work in .NET Core 2.0. This covers general usage of TelemetryClient and HTTP auto dependency/correlation tracking.

However, we found that with Microsoft.ServiceFabric.Services.Remoting 3.0 and above, the service remoting V1 API has been removed, only the service remoting V2 API is present. So for now it has no support for correlation over service remoting on the .NET core 2.0 templates.

We are working with the service fabric team on a solution.

**Comment by Eneuman** [comment]
Hi

I'm trying to use Microsoft.ApplicationInsights.ServiceFabric.Native 2.0.1-beta1 against a Service Fabric.Net Core 2 "netcoreapp2.0" service.
The problem is that the nuget package only supports: .NetFramework, Version 4.5 by the description of the dependencies.

Any chance we can get a Microsoft.ApplicationInsights.AspNetCore.ServiceFabric.Native thats works with .NetStandard Version 1.6 ?

**Comment by brahmnes** [comment]
Hi Eneuman,

Unfortunately because Microsoft.ApplicationInsights.ServiceFabric.Native has a dependency on the service remoting V1 API, it cannot be built against .NET standard right now. You can only use Microsoft.ApplicationInsights.ServiceFabric.

I agree and understand this is undesirable. We do have a goal to get Microsoft.ApplicationInsights.ServiceFabric.Native running on .NET standard.

**Comment by htuomola** [comment]
Good to see that this has already been raised but just wanted to add that I think enabling this will also enable support for Service Fabric V2 remoting itself (which people might be using also even without asp.net core 2.0, e.g. for custom serialization).

**Comment by brahmnes** [comment]
.NET core 2.0 is supported now. https://github.com/Microsoft/ApplicationInsights-ServiceFabric/releases/tag/2.1.0-beta1
