### ISSUE TITLE
[Proposal] TelemetryInitializer to set Component.Version from CodePackageVersion

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/ApplicationInsights-ServiceFabric#41]
I suggest to add a TelemetryInitializer that sets the ITelemetry.Context.Component.Version based on the CodePackageVersion.

Very simple version:

public class ServiceFabricComponentVersionTelemetryInitializer : ITelemetryInitializer
{
   public void Initialize(ITelemetry telemetry)
   {
      var activationContext = FabricRuntime.GetActivationContext();
      telemetry.Context.Component.Version = activationContext.CodePackageVersion;
   }
}

**Comment by brahmnes** [comment]
Hi Mikael,

Thank you and this is a good suggestion. Do you mind submitting a PR?

**Comment by brahmnes** [comment]
2.0.1-beta1 has been released with this change.
