### ISSUE TITLE
Service Remoting v2 Support

### ISSUE THREAD

**Issue by berndku** [Microsoft/ApplicationInsights-ServiceFabric#48]
It seems CorrelatingServiceProxyFactory and CorrelationgActorProxyFactory support only Service Remoting V1. What are the plans to support Service Remoting v2 in addition to Remoting v1 ?

**Comment by brahmnes** [comment]
This is currently being looked at. See related issue:
https://github.com/Microsoft/ApplicationInsights-ServiceFabric/issues/36

**Comment by yantang-msft** [comment]
Trace correlations are supported in V2 now. https://github.com/Microsoft/ApplicationInsights-ServiceFabric/releases/tag/2.1.0-beta1
