### ISSUE TITLE
Unable to reproduce sample from documentation

### ISSUE THREAD

**Issue by mgrishkov** [Microsoft/ApplicationInsights-ServiceFabric#49]
Dear team, I've repeated all steps from "[Monitor and diagnose an ASP.NET Core application on Service Fabric](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-monitoring-aspnet)" till the paragraph "View telemetry and the App map in Application Insights". As described in documentation at the step I should see events in Azure Application Insight. Unfortunately, I didn't see anything. 
Debug output window shows following messages:
`
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2017-11-29T08:55:26.8391314Z","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.role":"fabric:/Voting/VotingData","ai.cloud.roleInstance":"131564192630191563","ai.operation.id":"17993589-47f0a8360afffd48","ai.operation.name":"GET VoteData/Get","ai.location.ip":"::1","ai.internal.sdkVersion":"aspnet5f:2.2.0-beta1","ai.internal.nodeName":"XXXXXX.XXXXXX.local"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|17993589-47f0a8360afffd48.","name":"GET VoteData/Get","duration":"00:00:00.1632013","success":true,"responseCode":"200","url":"http://localhost:53576/c27e2db5-828a-4a69-b69d-7ba70c1eacce/131564192630191563/c11387c2-1aee-4ffa-b91b-f2e1c1029541/api/VoteData","properties":{"ServiceFabric.ServiceName":"fabric:/Voting/VotingData","ServiceFabric.ApplicationTypeName":"VotingType","ServiceFabric.ServiceTypeName":"VotingDataType","ServiceFabric.PartitionId":"c27e2db5-828a-4a69-b69d-7ba70c1eacce","httpMethod":"GET","ServiceFabric.ApplicationName":"fabric:/Voting","ServiceFabric.ReplicaId":"131564192630191563","AspNetCoreEnvironment":"Development","DeveloperMode":"true","ServiceFabric.NodeName":"_Node_0"}}}}
Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor: Information: Executing JsonResult, writing value System.Collections.Generic.List`1[System.Collections.Generic.KeyValuePair`2[System.String,System.Int32]].
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executed action VotingWeb.Controllers.VotesController.Get (VotingWeb) in 262.2165ms
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 288.6173ms 200 application/json; charset=utf-8
Exception thrown: 'System.IO.IOException' in mscorlib.dll
'VotingData.exe' (CLR v4.0.30319: VotingData.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_ru_b77a5c561934e089\System.resources.dll'. Module was built without symbols.
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
Exception thrown: 'System.NullReferenceException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.AI.PerfCounterCollector.dll
Exception thrown: 'System.InvalidOperationException' in System.dll
`
What am I doing wrong?
Repository with sample you can [see here](https://github.com/mgrishkov/sf-applicationinsight).

P.S. I have to hide pc and domain name with XXXXXX.XXXXXX.local

**Comment by mgrishkov** [comment]
Hey, Are there anyone?

**Comment by karolz-ms** [comment]
Looks like PerfCounterCollector has trouble.

@SergeyKanzhelev @cijothomas @Dmitry-Matveev any idea how to diagnose this?

**Comment by SergeyKanzhelev** [comment]
@mgrishkov I see two separate issues here: 
1. log says `(unconfigured)` meaning that instrumentation key was not set properly. Please make sure proper instrumentation key was set in `ApplicationInsights.config` or `settings.json` on [this](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-monitoring-aspnet#add-application-insights-to-the-applications-services) step. If it's `settings.json` - make sure it will be read and applied in your DI.

2. Invalid operation exception happening. This is just a debug message, not an unhandled error. It may be some AI infrastructure exception that does not affect the main application logic

**Comment by mgrishkov** [comment]
@SergeyKanzhelev you are right the cause of the error was invalid Application Insight configuration.
Now everything works fine.
