### ISSUE TITLE
Add Live Stream support to OWIN based Services

### ISSUE THREAD

**Issue by fbeltrao** [Microsoft/ApplicationInsights-ServiceFabric#58]
In OWIN based web application requests will not show up in the Application Insights Live Stream.
A solution to this problem is to use a QuickPulseTelemetryModule on the application like this [post describes](http://apmtips.com/blog/2017/02/13/enable-application-insights-live-metrics-from-code)

Ideally this should be built-in, or at least have a reference implementation in this repository.

**Comment by brahmnes** [comment]
Yes, what you said is correct.
We can start with a pointer to the blog post link you mentioned. Do you want to submit a PR to our readme?

**Comment by fbeltrao** [comment]
@brahmnes: I figured out that you can do it without code, just changes to the Application Insights config file. I will submit a PR
