### ISSUE TITLE
Could not load file or assembly 'Microsoft.AI.ServiceFabric.Native, Version=2.1.0.0, Culture=neutral, PublicKeyToken=f23a46de0be5d6f3' or one of its dependencies.

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/ApplicationInsights-ServiceFabric#60]
Hey,
I'm getting an error when trying to use Microsoft.AI.ServiceFabric.Native in a `.NET Framework` service. My `.NET Core` services are working just fine.

Here is the error:
> System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Microsoft.AI.ServiceFabric.Native, Version=2.1.0.0, Culture=neutral, PublicKeyToken=f23a46de0be5d6f3' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=Microsoft.Intentional.Services.Utilities.ServiceFabric
  StackTrace:
   at Microsoft.Intentional.Services.Utilities.ServiceFabric.Logging.ServiceRemotingDependencyExtensions.AddServiceRemotingTelemetry(IServiceCollection services)
   at Microsoft.Intentional.Services.Shared.IntentionalWebHostBuilder.<>c__DisplayClass0_0`1.<CreateWebHostBuilder>b__2(IServiceCollection services) in C:\Users\joschm\Intentional\services\src\IntentionalServices.Shared\IntentionalWebHostBuilder.cs:line 47

Here is the FusionLog:

> === Pre-bind state information ===
LOG: DisplayName = Microsoft.AI.ServiceFabric.Native, Version=2.1.0.0, Culture=neutral, PublicKeyToken=f23a46de0be5d6f3
 (Fully-specified)
LOG: Appbase = file:///C:/SfDevCluster/Data/_App/_Node_0/IntentionalServicesType_App2/ContentValidationServicePkg.Code.1.0.0/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Intentional.Services.Utilities.ServiceFabric, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\SfDevCluster\Data\_App\_Node_0\IntentionalServicesType_App2\ContentValidationServicePkg.Code.1.0.0\ContentValidationService.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.AI.ServiceFabric.Native, Version=2.1.0.0, Culture=neutral, PublicKeyToken=f23a46de0be5d6f3
LOG: Attempting download of new URL file:///C:/SfDevCluster/Data/_App/_Node_0/IntentionalServicesType_App2/ContentValidationServicePkg.Code.1.0.0/Microsoft.AI.ServiceFabric.Native.DLL.
WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

If I look in the pacakge folder, I see the following AI DLLs:

.NET Framework Service (which is not working):

|ProductVersion  | FileVersion   |   FileName |
|--------------  | -----------   |   -------- |
|2.4.0.105563    | 2.4.0.105563  |   C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentValidationServicePkg\Code\Microsoft.AI.Agent.Intercept.dll |
|2.5.1.195       | 2.5.1.195     |   C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentValidationServicePkg\Code\Microsoft.AI.DependencyCollector.dll |
|2.5.1.195       | 2.5.1.195     |   C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentValidationServicePkg\Code\Microsoft.AI.PerfCounterCollector.dll |
|2.5.1.172       | 2.5.1.172     |   C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentValidationServicePkg\Code\Microsoft.AI.ServerTelemetryChannel.dll |
|2.1.0.140       | 2.1.0.140     |   C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentValidationServicePkg\Code\Microsoft.AI.ServiceFabric.dll |
|2.1.0.140       | 2.1.0.140     |   C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentValidationServicePkg\Code\Microsoft.AI.ServiceFabric.Native.dll |

.NET Core Service (which is working):

| ProductVersion |  FileVersion     | FileName |
| -------------- |  -----------     | -------- |
| 2.5.1          |  2.5.1.195       | C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentServiceFrontendPkg\Code\Microsoft.AI.DependencyCollector.dll |
| 2.5.1          |  2.5.1.195       | C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentServiceFrontendPkg\Code\Microsoft.AI.PerfCounterCollector.dll |
| 2.5.1.172      |  2.5.1.172       | C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentServiceFrontendPkg\Code\Microsoft.AI.ServerTelemetryChannel.dll |
| 1.0.0          |  2.1.0.140       | C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentServiceFrontendPkg\Code\Microsoft.AI.ServiceFabric.dll |
| 1.0.0          |  2.1.0.140       | C:\Users\joschm\Intentional\services\src\IntentionalServices\pkg\Debug\ContentServiceFrontendPkg\Code\Microsoft.AI.ServiceFabric.Native.dll |

So the big different I see here is the ProductVersion - is that wrong?

**Comment by yantang-msft** [comment]
Did you replace this service fabric dll? It's not strong name signed.
Calling assembly : Microsoft.Intentional.Services.Utilities.ServiceFabric, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.

**Comment by Tadimsky** [comment]
No, I did not do anything special other than add the nuget package references.

**Comment by yantang-msft** [comment]
The .net core Servicefabric.Native.dll is indeed not signed. The fix is released with version 2.1.1-beta1. Thank you for reporting this issue.

**Comment by Tadimsky** [comment]
That seems to have fixed it for me! Thank you :)
