### ISSUE TITLE
Disable unnecessary performance counters in default configuration

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-ServiceFabric#61]
Moved from https://github.com/Microsoft/ApplicationInsights-Home/issues/166

Originally reported by @Eneuman

>We have a project containing 12 Service Fabric applications and 40 services running on 5 servers.
>Using the default setup for Application Insights results in 200 services sending the same performance telemetry, like server CPU and server avail mem, to AI witch uses up all of our AI storage.
>All services are using .Net Core 2.
>We need to reduce the amount of performance data that gets transmitted to AI, but all exceptions (with stacktraces) and requests must be send.
>Can this be done and in that case; what is the recommended way of handeling this?
>We would like to see the following performance data in AI:
> - CPU load of each server
> - CPU load of each service
> - Avail mem of each server
> - Used mem for each service

**Comment by yantang-msft** [comment]
@Eneuman You can clear the default perf counters and add the CPU/Mem counters for each services like below, and use WAD to collect CPU/Mem for each server.
``` c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    ...
    var modules = app.ApplicationServices.GetServices<ITelemetryModule>();
    var perfModule = modules.OfType<PerformanceCollectorModule>().First();
    perfModule.DefaultCounters.Clear();
    perfModule.Counters.Add(new PerformanceCounterCollectionRequest(@"\Process(IntanceName)\Private Bytes", @"\Process(IntanceName)\Private Bytes"));
    perfModule.Counters.Add(new PerformanceCounterCollectionRequest(@"\Process(InstanceName)\% Processor Time", @"\Process(InstanceName)\% Processor Time"));
}
```

Or you can just use WAD to collect perf counters for both server and all services. In this case, you can simply remove the perf counter module
``` c#
public void ConfigureServices(IServiceCollection services)
{
    ...
    var serviceDescriptor = services.FirstOrDefault(descriptor => descriptor.ImplementationType == typeof(PerformanceCollectorModule));
    services.Remove(serviceDescriptor);
}
```

**Comment by brahmnes** [comment]
@Eneuman,
Using WAD with Service Fabric can be found here:
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostics-event-aggregation-wad

I assume the question is now answered and I am closing this issue. If you think it's not, please feel free to reactivate.
