### ISSUE TITLE
Timeline for non-preview release

### ISSUE THREAD

**Issue by Expecho** [Microsoft/ApplicationInsights-ServiceFabric#66]
Hi there, just want to know what the roadmap & timeline is for this package. What needs to be done before a non-preview nuget can be released?

**Comment by brahmnes** [comment]
Hi @Expecho 
We are working through a few more bugs, which after that we make this a non-preview.
Thank you and everyone for providing feedback and filing issues, which enabled us to discover and fix these issues.

**Comment by Expecho** [comment]
Ok great to hear, I really appreciate the work you guys did!
