### ISSUE TITLE
How to configure on stateless remoting v2 service

### ISSUE THREAD

**Issue by vitorrossetto2** [Microsoft/ApplicationInsights-ServiceFabric#69]
Hi,

Even reading the documentation i could not figure out where i have to configure the telemetry client to monitor my stateless project with remoting v2.

It don't have a WebHostBuilder to UseApplicationInsights() and services.AddApplicationInsightsTelemetry(chaveInstrumentacaoApplicationInsights);

please help me!

Thanks.

**Comment by yantang-msft** [comment]
@vitorrossetto2 Checkout this example and see if it helps.
https://github.com/yantang-msft/service-fabric-application-insights-example/blob/master/StatelessBackend/StatelessBackend.cs#L30

**Comment by vitorrossetto2** [comment]
Hi, 

Thank you, i managed to make it work with this tip but it still dont map the database requests =(

any idea what is happening?

here is the print of application map:

https://ibb.co/iYdMqo

thank you so much

**Comment by yantang-msft** [comment]
@vitorrossetto2 What do you mean by "map the database requests"? Do you mean you are calling sql database but the sql db node is not showing up?

**Comment by vitorrossetto2** [comment]
yes, these microservices are making requests to sql server databases via dapper and entity framework but the nodes dont appear in application insights.

**Comment by yantang-msft** [comment]
The example only added the SF specific modules (that tracks the Service Remoting calls).
The sql requests are more general dependency calls and they are captured by the DependencyCollectorModule. If you add the AI AspNetCore package, it will bring in that module automatically.
I've updated my example, checkout the StatelessBackend service to see how it is setup.
