### ISSUE TITLE
Microsoft.ApplicationInsights.ServiceFabric.FabricTelemetryInitializer exists in multiple assemblies

### ISSUE THREAD

**Issue by Lillvik** [Microsoft/ApplicationInsights-ServiceFabric#73]
Microsoft.ApplicationInsights.ServiceFabric.FabricTelemetryInitializer is available in the following assemblies.
Microsoft.AI.ServiceFabric.Native
Microsoft.AI.ServiceFabric

Since Microsoft.ApplicationInsights.ServiceFabric.Native has dependency to Microsoft.ApplicationInsights.ServiceFabric both the assemblies above are included when Microsoft.ApplicationInsights.ServiceFabric.Native is added to a project.

This results in the following error 

The type 'FabricTelemetryInitializer' exists in both 'Microsoft.AI.ServiceFabric.Native, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.AI.ServiceFabric, Version=2.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by yantang-msft** [comment]
@Lillvik Can you try using ```FabricTelemetryInitializerExtension.CreateFabricTelemetryInitializer(this.Context)``` instead of creating the TelemetryIntializer directly?

**Comment by yantang-msft** [comment]
Fixed in https://github.com/Microsoft/ApplicationInsights-ServiceFabric/pull/75
