### ISSUE TITLE
Accessing the current request telemetry object created via the Service Bus

### ISSUE THREAD

**Issue by jstawski** [Microsoft/ApplicationInsights-ServiceFabric#77]
We have a Service Fabric Stateless Service running .NET Core (not ASP.NET). It's sole purpose is to process data in the background when a Service Bus message is received. We are using the latest SDK of the Service Bus and Application Insights and following the Message Handler Pattern. This works like a charm with Insights as it automagically creates a request when a message is received and correlates all Exceptions, Traces, and Dependency calls with the same request. Kudos to the team for that.

Now we want to be able to change the `Success` and `ResponseCode` of the underlying `RequestTelemetry` object if an Exception is thrown or with our business rules. How do we do that?

**Comment by yantang-msft** [comment]
@lmolkova Could you give some insights?
This question is out of scope of this repo but more Service Bus related. The main purpose for this repo is adding SF context information and correlation for SF remoting.

**Comment by jstawski** [comment]
I don't think it belongs to Service Bus, but rather to Application Insights, but I might be wrong.

**Comment by lmolkova** [comment]
@jstawski Happy to hear it works for you!

You should be able to achieve it with custom telemetry processor: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-api-filtering-sampling

Let me know if you need more info.
Also, would you mind sharing your scenario?  What would you like to see in Success and ResponseCode?

**Comment by jstawski** [comment]
@lmolkova thanks for the reply, I will check it out. More specifically I would like for the `Success` to be set as `false` if the processing failed due to an unknown exception as the message was not processed successfully.

**Comment by lmolkova** [comment]
@jstawski 
My  understanding was that success should be set to false if handler Task is not RunToCompletion: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/0e10db7d201dfd8104b71185668738d44fbf6ee4/Src/DependencyCollector/Shared/Implementation/EventHandlers/DiagnosticsEventHandlerBase.cs#L82
So it seems there is some bug if Success is not set.

If you handle the exception in the processing handler, though. You may use `Activity.Current.AddTag("success", "false")` and `Activity.Current.AddTag("ResponseCode", ex.Message)`

and in the TelemteryProcessor/TelemetryIntitializer, look for these tags on Activity,Current and set them on RequestTelmetry

**Comment by lmolkova** [comment]
@jstawski right, so when the exception is handled, it results in the successful Request telemetry, unfortunately. I'll think what we can do here.

[Activity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) is an .NET API created to carry correlation details and flow with async calls. It is managed by ServiceBus SDK and consumed by ApplicationInsights. It is created for message processing and dies after is it completed, so you don't have to (and cannot) clean up tags

**Comment by jstawski** [comment]
Thank you @lmolkova! The Activity solution worked like a charm.
