### ISSUE TITLE
[Bug] Service Remoting dependencies displayed differently in App Map between ASP.NET Core and non-ASP.NET Core services

### ISSUE THREAD

**Issue by WhitWaldo** [Microsoft/ApplicationInsights-ServiceFabric#78]
I'm a big fan of using the Application map to identify the dependencies between my Service Fabric microservices, but one of the biggest quirks to it that I've identified is the disconnect between non-ASP.NET Core services and their various dependency calls between ASP.NET Core and non-ASP.NET Core services. Specifically, call from an ASP.NET Core service to another non-ASP.NET Core service will show up as a dependency between App.ServiceA and App.ServiceB, but a similar call between two non-ASP.NET Core services will show up as a call from App.ServiceB to fabric:/App/ServiceC, but App.Service will show up elsewhere on the graph (attached to App.ServiceA since there are other calls made directly to it from A).

To illustrate my point, I've attached a sanitized sample of my application map:

![image](https://user-images.githubusercontent.com/2238529/42739270-f3c94f90-8859-11e8-9298-15b96f8aea4f.png)

In this example, I have three services running:
- App.ServiceA is an ASP.NET Core application running as a stateless service
- App.ServiceB is stateless service (notably not running ASP.NET Core, but utilizing Service Fabric Remoting for inter-service communication)
- App.ServiceC is a stateful service (again, not running ASP.NET Core, but utilizing Service Fabric Remoting for communication)

I have two methods that will come into the API controller in ServiceA. One of them will make a call to App.ServiceB (via remoting) which will, in turn, make a call to ServiceC and return the results. The other method will directly call ServiceC and return those results. 

**Expected:**
Just as App.ServiceA is directly connected to App.ServiceB and App.ServiceC in the above image, I'd expect to see App.ServiceB directly connected to App.ServiceC with a one-way arrow instead of this arbitrary dead-end dependency call to fabric:/App/ServiceC (as though App.ServiceC and fabric:App/ServiceC aren't the same thing, which they are).

Thanks!

**Comment by yantang-msft** [comment]
@WhitWaldo How is ServiceB communicating to ServiceC? Http or Service Remoting?
Supposing all the data are sent to the same AppInsights Resource, can you run these queries in Log Analytics and share the result? You may need to change the 'target' field to the correct value.
```
dependencies
| where cloud_RoleName == "App.ServiceA" and target contains "fabric:/App/ServiceC"
| where cloud_RoleName == "App.ServiceB" and target contains "fabric:/App/ServiceC"
```
```
requests
| where cloud_RoleName == "App.ServiceC"
```

**Comment by WhitWaldo** [comment]
@yangtang-msft All services communicate exclusively through Service Remoting. 

With regards to your request for data, do you have a secure upload location I could share the data to? I'd rather not publish it all publicly.

**Comment by yantang-msft** [comment]
@WhitWaldo You can use `project` to filter out sensitive information.
@madeleinefletcher Can you work with @WhitWaldo and see whether it's a bug of App Map?

**Comment by yantang-msft** [comment]
@anomalizer Is it possible that you share your project that has issue with us?
My gut feeling is that the non ASP stateless service is not configured correctly. The configuration story for non Asp.Net /Asp.Net core application is a bit complicated. You can take a look at this [doc](https://docs.microsoft.com/en-us/azure/application-insights/application-insights-console) or this [repo](https://github.com/yantang-msft/service-fabric-application-insights-example/blob/master/StatelessBackend/StatelessBackend.cs) for some examples.

**Comment by anomalizer** [comment]
Thanks @yantang-msft. Your code example works. FWIW I made this change. Am not sure if the first list is required
```c#
        protected override IEnumerable<ServiceInstanceListener> CreateServiceInstanceListeners()
        {
            FabricTelemetryInitializerExtension.SetServiceCallContext(this.Context);
            return this.CreateServiceRemotingInstanceListeners();
        }
```

**Comment by yantang-msft** [comment]
@anomalizer The first line is required, that how AppInsights set the service name, i.e., App.ServiceA.

**Comment by WhitWaldo** [comment]
I ultimately opened a ticket with the App Insights team via Azure support and identified the issue as one with how I was specifying the parent and operation IDs across services (having flipped the two in practice). As a result, everything is now displaying as I'd expect in the App Map.
