### ISSUE TITLE
Provide documentation on integrating AI with service fabric

### ISSUE THREAD

**Issue by balukantu** [microsoft/ApplicationInsights-ServiceFabric#80]
I am unable to figure out how to integrate AI using Microsoft.ApplicationInsights.ServiceFabric.Native Nuget. 

Can someone you provide how to configure AI with instrumentation key and log traces.

**Comment by brahmnes** [comment]
Hi @balukantu,
Have you looked at the readme on https://github.com/Microsoft/ApplicationInsights-ServiceFabric#net-core?
Do you have more specific questions? Which part are you stuck on?

**Comment by yantang-msft** [comment]
@balukantu It depends on your project, whether it's a console app, or ASP .Net, or ASP .Net Core?
The Microsoft.ApplicationInsights.ServiceFabric.Native is an additive package and needs extra configuration, which is documented at [here](https://github.com/Microsoft/ApplicationInsights-ServiceFabric#microsoftapplicationinsightsservicefabricnative---for-service-fabric-reliable-services)

**Comment by brahmnes** [comment]
Hi @balukantu,

Can you tell us if you are using ASP.NET core or ASP.NET?
Initialization of ApplicationInsights can be different depending on the project type.

**Comment by balukantu** [comment]
@brahmnes I am developing native fabric application (.Net Framework)

**Comment by brahmnes** [comment]
Hi @balukantu,

Even a fabric application can use ASP.NET or ASP.NET core.
Here is a question: Does your project have web.config in it? If you look at the packages.config file, does it have references to Microsoft.AspNet.* packages?

The fact that you are using OwinCommunicationListener suggests to me that you may be using Microsoft.AspNet.WebApi.Owin, but I am not sure.

**Comment by balukantu** [comment]
@brahmnes , Yes, I have below references and I am using OwinCommunicationListener.
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.6" targetFramework="net462" />
  <package id="Microsoft.AspNet.WebApi.OwinSelfHost" version="5.2.6" targetFramework="net462" />

**Comment by brahmnes** [comment]
@balukantu,
I suspect you just haven't enabled Application Insights for your OWIN app.
See this link:
https://stackoverflow.com/questions/29471811/how-do-i-enable-application-insights-server-telemetry-on-webapi-project-that-use

**Comment by brahmnes** [comment]
Closing this issue since it's been inactive and presumably the issue was resolved.
