### ISSUE TITLE
Service Fabric Version Dependency

### ISSUE THREAD

**Issue by AdXone** [Microsoft/ApplicationInsights-ServiceFabric#81]
Looking to add the Native package to our .Net Core Web API, dependency says >= SF 3.0.467 and our project is using 3.2.176. Got conflict error below, then did as suggested (install Microsoft.ServiceFabric.Diagnostics.Internal 3.2.176 directly) but now have warnings about versions, am I supposed to just ignore the errors?

**Initial Error trying to Add..**
Version conflict detected for Microsoft.ServiceFabric.Diagnostics.Internal. Install/reference Microsoft.ServiceFabric.Diagnostics.Internal 3.2.176 directly to project WebAPI to resolve this issue. 
 WebAPI -> Microsoft.ServiceFabric.Services 3.2.176 -> Microsoft.ServiceFabric.Diagnostics.Internal (= 3.2.176) 
 WebAPI -> Microsoft.ApplicationInsights.ServiceFabric.Native 2.1.1 -> Microsoft.ServiceFabric.Services.Remoting 3.0.467 -> Microsoft.ServiceFabric.Diagnostics.Internal (= 3.0.467).

**Now get Warnings...**
Detected package version outside of dependency constraint: Microsoft.ServiceFabric.Services.Remoting 3.0.467 requires Microsoft.ServiceFabric.Services (= 3.0.467) but version Microsoft.ServiceFabric.Services 3.2.176 was resolved.

**Comment by yantang-msft** [comment]
@AdXone Yes, you can ignore this warning. But I would upgrade the ```Microsoft.ServiceFabric.Services.Remoting ``` package 3.2.176, so there should be no warnings.
