### ISSUE TITLE
Microsoft.ApplicationInsights.ServiceFabric.Native 2.1.1 causes version conflict on Microsoft.ServiceFabric.Diagnostics.Internal

### ISSUE THREAD

**Issue by dguerin** [Microsoft/ApplicationInsights-ServiceFabric#82]
When adding Microsoft.ApplicationInsights.ServiceFabric.Native 2.1.1 to a new Stateless Service I'm getting version conflicts which are listed below.

Note: I'm using the latest Service Fabric SDK 3.2.176

```
Error	NU1107	Version conflict detected for Microsoft.ServiceFabric.Diagnostics.Internal. Install/reference Microsoft.ServiceFabric.Diagnostics.Internal 3.2.176 directly to project Web1 to resolve this issue. 
 Web1 -> Microsoft.ServiceFabric.AspNetCore.Kestrel 3.2.176 -> Microsoft.ServiceFabric.AspNetCore.Abstractions 3.2.176 -> Microsoft.ServiceFabric.Services 3.2.176 -> Microsoft.ServiceFabric.Diagnostics.Internal (= 3.2.176) 
 Web1 -> Microsoft.ApplicationInsights.ServiceFabric.Native 2.1.1 -> Microsoft.ServiceFabric.Services.Remoting 3.0.467 -> Microsoft.ServiceFabric.Diagnostics.Internal (= 3.0.467).	Web1 C:\[pathtto.csproj] 1
```

Also getting a smaller dependency constraint as follows:

```
Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.ServiceFabric.FabricTransport.Internal 3.0.467 requires Microsoft.ServiceFabric (= 6.1.467) but version Microsoft.ServiceFabric 6.3.176 was resolved.	Web1	C:\[pathtto.csproj]	1	
```

**Comment by yantang-msft** [comment]
@dguerin Please reference the package directly in your project as stated:
```Install/reference Microsoft.ServiceFabric.Diagnostics.Internal 3.2.176 directly to project Web1 to resolve this issue. ```.
You may want to update all SF packages to 3.2.176, for example, ```Microsoft.ServiceFabric.FabricTransport.Internal```, ```Microsoft.ServiceFabric.Services.Remoting```.

**Comment by dguerin** [comment]
Thanks @yantang-msft I saw that. The reason I added this issue is as a result of the description of these internal packages being described as internal only and shouldn't be used otherwise. As well as the dependency tree being locked to specific versions of Microsoft.ServiceFabric.* packages. For example as stated:

```
Microsoft.ServiceFabric.Diagnostics.Internal

This package provides Diagnostics functionality to be used by Service Fabric Actors and Service framework. This package is intended to be used by other official Microsoft ServiceFabric packages only.
```

What I've done in the end is as follows:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="3.2.176" />
    <PackageReference Include="Microsoft.ApplicationInsights.ServiceFabric.Native" Version="2.1.1" />
    <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="3.2.176" />
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="3.2.176" />
  </ItemGroup>
```

Should the Microsoft.ApplicationInsights.ServiceFabric.Native dependencies be locked to specific versions?

**Comment by yantang-msft** [comment]
@dguerin No, we can't lock the dependency to a specific version.
I think the real problem here is the ```Microsoft.ServiceFabric.Services.Remoting``` package locked its dependency ```Microsoft.ServiceFabric.Diagnostics.Internal``` to a specific version, thus you're asked to specify the ```Microsoft.ServiceFabric.Diagnostics.Internal``` version explicitly. And even if you do that, you will get a warning without updating the ```Microsoft.ServiceFabric.Services.Remoting``` package.
So if we lock the dependency version of the ```Microsoft.ApplicationInsights.ServiceFabric.Native``` package, you will almost always have a version conflict warning on the dependencies packages.

**Comment by dguerin** [comment]
@yantang-msft yes the real problem is in Remoting. Thanks for the help. I'll look into creating an issue there if one does not exist already.
