### ISSUE TITLE
FabricTelemetryInitializerExtension is missing or documentation is incorrect

### ISSUE THREAD

**Issue by vitalybibikov** [Microsoft/ApplicationInsights-ServiceFabric#86]
FabricTelemetryInitializerExtension is not presented for .NET Core, only for Native. It's a bit of a complication for Apps, that have both Reliable and Guest services.

Suggestion is to create a FabricTelemetryInitializerExtension that will take Context as an optional parameter.

So, there will be no need to support 2 ways of configurations

**Comment by yantang-msft** [comment]
@vitalybibikov FabricTelemetryInitializerExtension exists for .NET core apps. What's the version of the ServiceFabric.Native package you are using?
