### ISSUE TITLE
AI Not supported for .NET Core Stateless services?

### ISSUE THREAD

**Issue by Adebeer** [Microsoft/ApplicationInsights-ServiceFabric#89]
I'm currently using the Microsoft.ApplicationInsights.ServiceFabric and ServiceFabric.Native packages with Serilog and I have no problem sending events and traces from an ASP.NET Core application.

However, I can't get any telemetry from .net core Stateless services (i.e. not asp.net core). I've created a basic stateless service and used VS 2017 tooling to add app insights - but it doesn't seem to do anything.

Am I missing something? All the samples I've seen use asp.net core.

**Comment by yantang-msft** [comment]
@Adebeer Checkout this example and see if it helps: https://github.com/yantang-msft/service-fabric-application-insights-example/blob/master/StatelessBackend/StatelessBackend.cs

**Comment by Adebeer** [comment]
@yantan-msft
Thank you, this works perfectly!
