### ISSUE TITLE
The nuget package is hard dependent on service fabric 3.2.162, 3.2.187 is the latest version and has important bug fixes

### ISSUE THREAD

**Issue by brijeshb** [Microsoft/ApplicationInsights-ServiceFabric#90]

**Comment by yantang-msft** [comment]
@brijeshb I suppose you're having some problem upgrading the SF nuget package version. Checkout this https://github.com/Microsoft/ApplicationInsights-ServiceFabric/issues/82 with similar situation and the solution.
