### ISSUE TITLE
No samples on how to use GlobalProperties or ISupport.Properties

### ISSUE THREAD

**Issue by paolosalvatori** [Microsoft/ApplicationInsights-ServiceFabric#91]
Hi updated the NuGet package to the latest version of the library, recompiled my project and now I see the following warning in the Build window:

1>CallContextTelemetryInitializer.cs(20,13,20,41): warning CS0618: 'TelemetryContext.Properties' is obsolete: 'Use GlobalProperties to set global level properties. For properties at item level, use ISupportProperties.Properties.'

A few months ago, I created the following class to track custom properties to Application Insights:

```
using Microsoft.ApplicationInsights.Extensibility;
using Microsoft.ApplicationInsights.Channel;

namespace VotingWeb
{
    public class CallContextTelemetryInitializer : ITelemetryInitializer
    {
        public void Initialize(ITelemetry telemetry)
        {
            if (string.IsNullOrEmpty(ClassName) || string.IsNullOrEmpty(MethodName))
            {
                return;
            }
            telemetry.Context.Properties["CallContext.ClassName"] = ClassName;
            telemetry.Context.Properties["CallContext.MethodName"] = MethodName;
            ClassName = MethodName = null;
        } 
        internal static string ClassName { get; set; }
        internal static string MethodName { get; set; }
    }
}
```

From the warning, I do understand that there are better ways now to track global and item level properties. Could you please provide samples in the readme file or provide a link to a sample?
My microservices are written with ASP.NET core services. Thanks!
Paolo

**Comment by yantang-msft** [comment]
@paolosalvatori See if this helps https://github.com/Microsoft/ApplicationInsights-dotnet/issues/820#issuecomment-429939316
@SergeyKanzhelev @cijothomas Do you any official document for this particular feature?

**Comment by paolosalvatori** [comment]
Hi  @yantang-msft / @cijothomas This answers my question. Still it would be great to document this somewhere. For this reason, I don't close the issue yet, thanks!

**Comment by yantang-msft** [comment]
@paolosalvatori This repo only has SF specific features.
You can create an issue at https://github.com/Microsoft/ApplicationInsights-dotnet to get more attention.
Yes, there are many app insights repos and it's not easy enough to correlate the features with the repos. But [ApplicationInsights-dotnet](https://github.com/Microsoft/ApplicationInsights-dotnet) is the right place for this ask.

**Comment by zvolkov** [comment]
This should be reopened - there is still no documentation/example and the example the link points to does not use GlobalProperties. Also, when you say "global" or "more global" - what exactly do you mean? Is request-scope global? Or the duration of one app run? Or the entire app, ever, on all nodes? Could use some clarity please.

**Comment by yantang-msft** [comment]
@zvolkov This issue is irrelevant to the AI-SF repo, but rather this is the repo (https://github.com/Microsoft/ApplicationInsights-dotnet). Feel free to open an issue under the [AI-dotnet]( https://github.com/Microsoft/ApplicationInsights-dotnet) repo for tracking purpose.
