### ISSUE TITLE
Update SDK

### ISSUE THREAD

**Issue by mihai-cloudbrick** [Microsoft/ApplicationInsights-ServiceFabric#98]
Can you update to the latest Service Fabric SDK?

**Comment by brahmnes** [comment]
Hi @mihai-cloudbrick,

Do you mind sharing what problem you are encountering?
The Application Insights Service Fabric nuget allows future versions of Service Fabric SDK to be used with it. Here is the copy and paste of the dependency list from https://www.nuget.org/packages/Microsoft.ApplicationInsights.ServiceFabric.Native/2.2.2

.NETFramework 4.5
Microsoft.ApplicationInsights (>= 2.4.0 && < 3.0.0)
Microsoft.ApplicationInsights.ServiceFabric (>= 2.2.2)
Microsoft.ServiceFabric (>= 6.3.162)
Microsoft.ServiceFabric.Services.Remoting (>= 3.2.162)
System.Diagnostics.DiagnosticSource (>= 4.4.0)
.NETStandard 2.0
Microsoft.ApplicationInsights (>= 2.4.0 && < 3.0.0)
Microsoft.ApplicationInsights.ServiceFabric (>= 2.2.2)
Microsoft.ServiceFabric (>= 6.3.162)
Microsoft.ServiceFabric.Services.Remoting (>= 3.2.162)
System.Diagnostics.DiagnosticSource (>= 4.4.0)
System.Runtime.Caching (>= 4.5.0)

**Comment by mihai-cloudbrick** [comment]
Hi the problem is that I was trying to use it with the latest SDK and Runtime for .NetCore  and fails, dependency issues , so I took the solution and customize it for my needs.
Now all works fine.

Mihai Dumitrascu | CloudBrick
CEO & Founder | Azure Cloud Solution Architect | Dr.Taberei 42, Bucuresti, Romania | Tel. 0733775033
